name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install --verbose
        
    - name: Debug info
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Directory contents: $(ls -la)"
        echo "Package.json scripts:"
        npm run --silent
        echo "Vite location:"
        which vite || echo "vite not in PATH"
        echo "Node modules vite:"
        ls -la node_modules/.bin/vite || echo "vite not in node_modules/.bin"
        echo "NPM list vite:"
        npm list vite
        
    - name: Build
      run: npx vite build
      
    - name: Create gh-pages branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        cp -r dist/* .
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages --force
      if: github.ref == 'refs/heads/main'
