name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install --verbose
        
    - name: Debug info
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Directory contents: $(ls -la)"
        echo "Package.json scripts:"
        npm run --silent
        echo "Vite location:"
        which vite || echo "vite not in PATH"
        echo "Node modules vite:"
        ls -la node_modules/.bin/vite || echo "vite not in node_modules/.bin"
        echo "NPM list vite:"
        npm list vite
        
    - name: Build
      run: |
        echo "Current NODE_ENV: $NODE_ENV"
        echo "Setting NODE_ENV=production..."
        export NODE_ENV=production
        echo "NODE_ENV after export: $NODE_ENV"
        echo "Cleaning any previous builds..."
        rm -rf dist/
        echo "Building with Vite..."
        echo "Vite version: $(npx vite --version)"
        echo "Build command: npx vite build --mode production"
        npx vite build --mode production
        echo "Build output:"
        ls -la dist/
        echo "HTML content:"
        cat dist/index.html
        echo "Checking for base path in built files..."
        grep -r "src/main.jsx" dist/ || echo "No src/main.jsx found in dist"
        grep -r "beads" dist/ || echo "No 'beads' found in dist"
        echo "Checking Vite config being used..."
        cat vite.config.js
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
